# Custom Language File for Launcher Customizer

[ejs.app]
title = "KCINEMA Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/FRErlingx/KCINEMA-Launcher"
mediaTwitterURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/FRErlingx/KCINEMA-Launcher"
supportLink = "#"